version: '2'
services:
    examadmin-app:
        image: examadmin
        external_links:
            - examadmin-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/examadmin?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    examadmin-mysql:
        extends:
            file: mysql.yml
            service: examadmin-mysql
