version: '2'
services:
    examadmin-mysql:
        container_name: examadmin-mysql
        image: mysql:5.7.11
        # volumes:
        #     - ~/volumes/jhipster/examadmin/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=examadmin
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
